spring.application.name=reskill
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROK_PASS}
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.speech.enabled=false
spring.ai.openai.embedding.enabled=false

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:rafaelmacoto@gmail.com}
spring.mail.password=${APP_PASS_EMAIL}
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
